"""Generation API endpoints.

Routes
------
POST /api/jobs/{job_id}/generate        Generate a resume or cover letter for a job.
GET  /api/jobs/{job_id}/artifacts       List all artifacts for a job (current user).
GET  /api/artifacts                     List all artifacts for the current user.
GET  /api/artifacts/{artifact_id}       Retrieve a single artifact (ownership-guarded).
POST /api/artifacts/baseline            Upload a baseline PDF resume and score it.

Baseline replacement strategy: if a baseline already exists for the user,
it is deleted before the new one is created. This keeps the data model simple
(one baseline per user) while allowing the user to re-upload their resume at
any time. A soft-replace (update-in-place) would require patching content,
scores, and created_at together; deleting and re-creating is cleaner and
preserves the create-only pattern used throughout the rest of the codebase.
"""

from __future__ import annotations

import logging
import uuid

from fastapi import APIRouter, Depends, HTTPException, UploadFile, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.base import get_session
from app.db.models.user import User
from app.deps import (
    get_current_user,
    get_embedding_client,
    get_llm_client,
    get_pdf_renderer,
    get_vector_store,
)
from app.embeddings.base import EmbeddingClient
from app.generator.pdf import PdfRenderer
from app.generator.types import StyleConfig
from app.llm.client import LLMClient
from app.repositories.artifact import ArtifactRepository
from app.repositories.job import JobRepository
from app.schemas.artifact import ArtifactRead, GenerateRequest
from app.services.generation import generate_for_job, score_baseline
from app.services.resume_extract import extract_text_from_pdf
from app.vectorstore.base import VectorStore

logger = logging.getLogger(__name__)

router = APIRouter(tags=["generation"])

_PDF_CONTENT_TYPES = {"application/pdf", "application/x-pdf"}
_MAX_UPLOAD_BYTES = 10 * 1024 * 1024  # 10 MB


@router.post(
    "/api/jobs/{job_id}/generate",
    response_model=ArtifactRead,
    status_code=status.HTTP_201_CREATED,
)
async def generate_artifact(
    job_id: uuid.UUID,
    body: GenerateRequest,
    session: AsyncSession = Depends(get_session),  # noqa: B008
    current_user: User = Depends(get_current_user),  # noqa: B008
    llm: LLMClient = Depends(get_llm_client),  # noqa: B008
    embed: EmbeddingClient = Depends(get_embedding_client),  # noqa: B008
    store: VectorStore = Depends(get_vector_store),  # noqa: B008
    pdf: PdfRenderer = Depends(get_pdf_renderer),  # noqa: B008
) -> ArtifactRead:
    """Generate a resume or cover letter for the given job posting.

    Returns the persisted ArtifactRead with quality scores populated.
    """
    job_repo = JobRepository(session)
    job = await job_repo.get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Job posting not found.",
        )

    style = StyleConfig(
        tone=body.style.tone,
        length=body.style.length,
        emphasis=list(body.style.emphasis),
    )

    artifact = await generate_for_job(
        session=session,
        llm=llm,
        embed=embed,
        store=store,
        user_id=current_user.id,
        job=job,
        kind=body.kind,
        style=style,
        pdf=pdf,
    )
    await session.commit()
    await session.refresh(artifact)
    return ArtifactRead.model_validate(artifact)


@router.get("/api/jobs/{job_id}/artifacts", response_model=list[ArtifactRead])
async def list_job_artifacts(
    job_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),  # noqa: B008
    current_user: User = Depends(get_current_user),  # noqa: B008
) -> list[ArtifactRead]:
    """List all artifacts generated by the current user for a specific job."""
    repo = ArtifactRepository(session)
    artifacts = await repo.list_for_job(user_id=current_user.id, job_id=job_id)
    return [ArtifactRead.model_validate(a) for a in artifacts]


@router.get("/api/artifacts", response_model=list[ArtifactRead])
async def list_user_artifacts(
    session: AsyncSession = Depends(get_session),  # noqa: B008
    current_user: User = Depends(get_current_user),  # noqa: B008
) -> list[ArtifactRead]:
    """List all artifacts belonging to the current user (Documents view)."""
    repo = ArtifactRepository(session)
    artifacts = await repo.list_by_user(user_id=current_user.id)
    return [ArtifactRead.model_validate(a) for a in artifacts]


@router.get("/api/artifacts/{artifact_id}", response_model=ArtifactRead)
async def get_artifact(
    artifact_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),  # noqa: B008
    current_user: User = Depends(get_current_user),  # noqa: B008
) -> ArtifactRead:
    """Retrieve a single artifact by ID.

    Returns 404 if the artifact does not exist or belongs to another user.
    """
    repo = ArtifactRepository(session)
    artifact = await repo.get(artifact_id)
    if artifact is None or artifact.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Artifact not found.",
        )
    return ArtifactRead.model_validate(artifact)


@router.post(
    "/api/artifacts/baseline",
    response_model=ArtifactRead,
    status_code=status.HTTP_201_CREATED,
)
async def upload_baseline(
    file: UploadFile,
    session: AsyncSession = Depends(get_session),  # noqa: B008
    current_user: User = Depends(get_current_user),  # noqa: B008
    llm: LLMClient = Depends(get_llm_client),  # noqa: B008
) -> ArtifactRead:
    """Upload a PDF resume as the user's baseline artifact.

    Validates the file (non-empty, ≤10 MB, valid %PDF magic bytes), extracts
    plain text, stores the result as an is_baseline Artifact, and returns
    quality scores. If a baseline already exists, it is replaced (deleted
    then re-created) so each user has exactly one baseline at a time.
    """
    content_type = (file.content_type or "").lower()
    if content_type not in _PDF_CONTENT_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Only PDF uploads are accepted. Received content-type: '{content_type}'.",
        )

    data = await file.read(_MAX_UPLOAD_BYTES + 1)

    if len(data) == 0:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Empty file.",
        )

    if len(data) > _MAX_UPLOAD_BYTES:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="File exceeds the 10 MB limit.",
        )

    if not data.startswith(b"%PDF-"):
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail="File is not a valid PDF.",
        )

    try:
        resume_text = extract_text_from_pdf(data)
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc

    scores = await score_baseline(
        session=session,
        llm=llm,
        user_id=current_user.id,
        baseline_markdown=resume_text,
    )

    repo = ArtifactRepository(session)

    # Replace existing baseline if present (one baseline per user).
    existing = await repo.get_baseline(user_id=current_user.id)
    if existing is not None:
        await session.delete(existing)
        await session.flush()

    artifact = await repo.create(
        user_id=current_user.id,
        job_id=None,
        kind="resume",
        format="markdown",
        content=resume_text,
        is_baseline=True,
        scores=scores.model_dump(),
    )
    await session.commit()
    await session.refresh(artifact)
    return ArtifactRead.model_validate(artifact)
